# This is a basic workflow to help you get started with Actions

name: Clean workflow 

# Controls when the workflow will run
on: 
  workflow_dispatch:
jobs: 
  jobs_one:
    name: clone
    runs-on: Ubuntu-latest
    steps:
      - name: testing 
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf ericgchu.github.io 
            cd ../pub
            rm ericgchu.github.io
